### ISSUE TITLE
Feature request: Add RSS feed for Blog and Events section

### ISSUE THREAD

**Issue by thefranke** [shader-slang/shader-slang.github.io#26]
The News & Events is missing a way to subscribe via RSS/Atom feeds. Since the page is generated via Jekyll, it is easy to collect all entries from `_posts` and `_events` and offer them either as combined or separate feeds.

A simple example implementation can be found here:
https://www.johnvincent.io/jekyll/rss-feed-with-jekyll/

The line `{% for post in site.posts limit:1000 %}` would either need a separate combined list of posts and events or add another feed referencing `site.events`.

**Comment by csyonghe** [comment]
This is implemented.

**Comment by thefranke** [comment]
Thank you!
